[package]
name = "patract-pilot"
version = "0.1.0"
authors = ["Patract <https://github.com/patractlabs/patract>"]
edition = "2018"
description = ""
default-run = "patract-pilot"

[dependencies]
cli = { package = "patract-cli", path = "cli" }

[target.'cfg(target_arch="x86_64")'.dependencies]
cli = { package = "patract-cli", path = "cli", features = [ "wasmtime" ] }
