[package]
name = "jupiter-rpc"
version = "0.1.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "14.2.0"
jsonrpc-pubsub = "14.2.0"

sc-client-api = { version = "2.0.0-rc6" }
sc-rpc = { version = "2.0.0-rc6" }

sp-api = { version = "2.0.0-rc6" }
sp-runtime = { version = "2.0.0-rc6" }
sp-transaction-pool = { version = "2.0.0-rc6" }
sc-keystore = { version = "2.0.0-rc6" }
sp-blockchain = { version = "2.0.0-rc6" }
sc-rpc-api = { version = "0.8.0-rc6" }
sp-block-builder = { version = "2.0.0-rc6" }
sp-consensus = { version = "0.8.0-rc6" }
sc-consensus-epochs = { version = "0.8.0-rc6" }
#sc-consensus-babe = { version = "0.8.0-rc6" }
#sc-consensus-babe-rpc = { version = "0.8.0-rc6" }
#sp-consensus-babe = { version = "0.8.0-rc6" }
sc-finality-grandpa = { version = "0.8.0-rc6" }
sc-finality-grandpa-rpc = { version = "0.8.0-rc6" }

substrate-frame-rpc-system = { version = "2.0.0-rc6" }
pallet-transaction-payment-rpc = { version = "2.0.0-rc6" }
pallet-contracts-rpc = { version = "0.8.0-rc6" }

jupiter-primitives = { path = "../primitives" }

