[package]
name = "jupiter-dev"
version = "1.0.2"
authors = ["Patract <https://github.com/patractlabs>"]
edition = "2018"
description = ""

[dependencies]
cli = { package = "jupiter-dev-cli", path = "cli" }

[features]
runtime-benchmarks = [
  "cli/runtime-benchmarks"
]
