[package]
name = "jupiter-dev"
version = "1.0.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"
description = ""

[dependencies]
cli = { package = "jupiter-dev-cli", path = "cli" }

[features]
runtime-benchmarks = [
    "cli/runtime-benchmarks"
]
