[package]
name = "patract-dev"
version = "0.1.0"
authors = ["Patract <https://github.com/patractlabs/patract>"]
edition = "2018"
description = ""

[dependencies]
cli = { package = "patract-dev-cli", path = "cli" }

[features]
runtime-benchmarks = [
    "cli/runtime-benchmarks"
]
