[package]
name = "patract-prep"
version = "1.0.1"
authors = ["Patract <https://github.com/patractlabs/patract>"]
edition = "2018"
description = ""
default-run = "patract-prep"

[dependencies]
cli = { package = "patract-cli", path = "cli" }

[target.'cfg(target_arch="x86_64")'.dependencies]
cli = { package = "patract-cli", path = "cli", features = [ "wasmtime" ] }
