[package]
name = "jupiter-prep"
version = "1.0.3"
authors = ["Patract <https://github.com/patractlabs>"]
edition = "2021"
description = ""
default-run = "jupiter-prep"

[dependencies]
cli = { package = "jupiter-cli", path = "cli" }

[target.'cfg(target_arch="x86_64")'.dependencies]
cli = { package = "jupiter-cli", path = "cli", features = ["wasmtime"] }
