[package]
name = "patract-cli"
version = "1.0.0"
authors = ["Patract <https://github.com/patractlabs/patract>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
parking_lot = "0.10.0"
serde_json = "1.0"
hex-literal = "0.2.1"

sc-authority-discovery = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-basic-authorship = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-network = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus-babe = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-finality-grandpa = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-client-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-telemetry = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }

sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-inherents = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus-babe = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-finality-grandpa = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-authority-discovery = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }

sc-cli = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master", optional = true }
sc-service = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master", optional = true }

pallet-authority-discovery = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-im-online = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }

# vendor
# pallet-contracts = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-contracts = { path = "../../../vendor/substrate/frame/contracts" }

patract-primitives = { path = "../../../primitives" }
patract-runtime-common = { path = "../../../runtime/common" }
patract-executor = { path = "../executor" }
patract-rpc = { path = "../../../rpc" }

jupiter-runtime = { package = "jupiter-prep-runtime", path = "../../../runtime/jupiter-prep" }

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }

[features]
default = ["cli"]
cli = [
    "sc-cli",
    "sc-service",
    "patract-executor/wasmi-errno",
]
wasmtime = [
    "sc-cli/wasmtime",
    "sc-service/wasmtime",
    "patract-executor/wasmtime",
]
