[package]
name = "patract-executor"
version = "0.1.0"
authors = ["Patract <https://github.com/patractlabs/patract>"]
edition = "2018"

[dependencies]
frame-benchmarking = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-executor = { version = "0.8.0", git = "https://github.com/paritytech/substrate", branch = "master" }

patract-io = { path = "../../../primitives/io" }

jupiter-runtime = { package = "jupiter-pilot-runtime", path = "../../../runtime/jupiter-pilot" }

[features]
wasmtime = [
    "sc-executor/wasmtime",
]
wasmi-errno = [
    "sc-executor/wasmi-errno",
]
