[package]
name = "jupiter-executor"
version = "0.1.0"
authors = ["Jupiter <https://github.com/patractlabs/jupiter>"]
edition = "2018"

[dependencies]
frame-benchmarking = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sc-executor = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "master" }
jupiter-runtime = { path = "../../../runtime/jupiter" }
jupiter-io = { path = "../../../primitives/io" }

[features]
wasmtime = [
    "sc-executor/wasmtime",
]
wasmi-errno = [
    "sc-executor/wasmi-errno",
]
