[package]
name = "pallet-poa-rpc-runtime-api"
version = "0.1.0"
authors = ["Patract <https://github.com/patractlabs>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.1.0", default-features = false }

sp-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-std = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }

pallet-poa = { path = "../../", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",

	"sp-api/std",
	"sp-std/std",
	"sp-runtime/std",

	"pallet-poa/std",
]
