name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        toolchain: [nightly-2020-10-05]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
          override: true

      - name: Cache Dependencies & Build Outputs
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('./Cargo.lock') }}

      - name: Fetch Git Submodule
        run: git submodule update --init --remote

      - name: Check Code Format
        run: cargo fmt -- --check

      - name: Code Lint
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --all -vv

      - name: Test Benchmark Feature
        run: cargo build -p patract-dev --all-features

      - name: Test
        run: cargo test --all -vv
