name: Clippy Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Init
        run: git submodule init && git submodule update
      - uses: actions-rs/toolchain@v1
        with:
            components: clippy
            toolchain: nightly-2020-10-05
            target: wasm32-unknown-unknown
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
